#!/usr/bin/env python3
"""
tools/migrate_legacy/migrate.py (v2.1)

Agentic legacy-site migration into a Docusaurus repo structure.

Key features:
- Deterministic extraction (pandoc/pdftotext)
- Deterministic chunking (heading-based + size fallback)
- Cached LLM summarization per chunk + per document
- Constraints-driven many-to-one planning
- Synthesis rewrite per planned page
- Deterministic linkmap + link repair
- Strict overwrite policy via generated-marker line

Backends:
- vLLM (OpenAI-compatible server): POST /v1/chat/completions

Typical workflow:
  python tools/migrate_legacy/migrate.py run --dry-run true --page-types teachers.quick_start,get_started.index
  python tools/migrate_legacy/migrate.py run --dry-run false --overwrite true

Outputs (under out/):
  inventory.jsonl
  extracted_index.jsonl + extracted/*
  chunks_index.jsonl + chunks/<source_id>/chunk_XXX.md
  summaries/chunk/<source_id>/chunk_XXX.json
  summaries/doc/<source_id>.json
  plans.jsonl
  drafts_index.jsonl
  linkmap.json
  report.md

NOTE: This tool is designed to be deterministic + reviewable.
"""

from __future__ import annotations

import argparse
import dataclasses
import fnmatch
import hashlib
import json
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import requests
import yaml
from jsonschema import validate as jsonschema_validate


HERE = Path(__file__).resolve().parent

GENERATED_MARKER = (
    "<!-- Generated by tools/migrate_legacy/migrate.py; do not edit by hand unless you remove this line. -->"
)

# -----------------------------
# Utility functions
# -----------------------------

def now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_text(s: str) -> str:
    return sha256_bytes(s.encode("utf-8", errors="replace"))


def read_text(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def write_text(p: Path, s: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")


def run_cmd(cmd: List[str], cwd: Optional[Path] = None, timeout: int = 300) -> Tuple[int, str, str]:
    proc = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=timeout,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    return proc.returncode, proc.stdout, proc.stderr


def load_prompt(name: str) -> str:
    p = HERE / "prompts" / name
    if not p.exists():
        raise FileNotFoundError(p)
    return read_text(p)


def load_schema(name: str) -> Dict[str, Any]:
    p = HERE / "schemas" / name
    if not p.exists():
        raise FileNotFoundError(p)
    return json.loads(read_text(p))


def parse_first_json_object(text: str) -> Dict[str, Any]:
    """
    Extract and parse the first JSON object from model output.
    Assumes the model emits JSON object near the start.
    """
    s = text.strip()
    if not s:
        raise ValueError("Empty LLM output")

    if s.startswith("{"):
        depth = 0
        for i, ch in enumerate(s):
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    return json.loads(s[: i + 1])

    idx = s.find("{")
    if idx >= 0:
        return parse_first_json_object(s[idx:])

    raise ValueError("Could not locate JSON object in LLM output")


def safe_relpath(p: Path) -> str:
    return str(p).replace("\\", "/")


# -----------------------------
# Config and constraints
# -----------------------------

@dataclasses.dataclass
class AppConfig:
    legacy_root: Path
    target_repo_root: Path
    output_dir: Path
    cache_dir: Path

    allowed_dest_prefixes: List[str]
    include_globs: List[str]
    exclude_globs: List[str]

    tools: Dict[str, str]
    llm: Dict[str, Any]
    pipeline: Dict[str, Any]
    first_wave: Dict[str, Any]

    chunking: Dict[str, Any]
    summarization: Dict[str, Any]

    constraints_file: Optional[Path]


def load_config(config_path: Path) -> AppConfig:
    raw = yaml.safe_load(read_text(config_path))

    legacy_root = (config_path.parent / raw["legacy_root"]).resolve()
    target_repo_root = (config_path.parent / raw["target_repo_root"]).resolve()
    output_dir = (config_path.parent / raw["output_dir"]).resolve()
    cache_dir = (config_path.parent / raw["cache_dir"]).resolve()

    constraints_file = None
    if "constraints_file" in raw and raw["constraints_file"]:
        constraints_file = (config_path.parent / raw["constraints_file"]).resolve()

    chunking = raw.get("chunking", {"chunk_chars": 7000, "overlap_chars": 500, "max_chunks_per_doc": 30})
    summarization = raw.get("summarization", {"chunk_summary_tokens": 350, "doc_summary_tokens": 450, "temperature": 0.1})

    return AppConfig(
        legacy_root=legacy_root,
        target_repo_root=target_repo_root,
        output_dir=output_dir,
        cache_dir=cache_dir,
        allowed_dest_prefixes=raw["allowed_dest_prefixes"],
        include_globs=raw["include_globs"],
        exclude_globs=raw["exclude_globs"],
        tools=raw["tools"],
        llm=raw["llm"],
        pipeline=raw["pipeline"],
        first_wave=raw["first_wave"],
        chunking=chunking,
        summarization=summarization,
        constraints_file=constraints_file,
    )


@dataclasses.dataclass
class Constraints:
    global_strict_allowlist: bool
    global_exclude_patterns: List[str]
    global_archive_patterns: List[str]
    pages: Dict[str, Any]

    @staticmethod
    def load(path: Optional[Path]) -> "Constraints":
        if not path:
            return Constraints(False, [], [], {})
        raw = yaml.safe_load(read_text(path))
        g = raw.get("global", {})
        return Constraints(
            global_strict_allowlist=bool(g.get("strict_allowlist", False)),
            global_exclude_patterns=list(g.get("exclude_patterns", [])),
            global_archive_patterns=list(g.get("archive_patterns", [])),
            pages=dict(raw.get("pages", {})),
        )

    def page_cfg(self, page_type: str) -> Dict[str, Any]:
        return self.pages.get(page_type, {})

    def force_include(self, page_type: str) -> List[str]:
        return list(self.page_cfg(page_type).get("force_include", []))

    def prefer_patterns(self, page_type: str) -> List[str]:
        return list(self.page_cfg(page_type).get("prefer_include_patterns", []))

    def forbid_patterns(self, page_type: str) -> List[str]:
        return list(self.page_cfg(page_type).get("forbid_patterns", []))

    def dest_override(self, page_type: str) -> Optional[str]:
        v = self.page_cfg(page_type).get("dest_override")
        return str(v) if v else None


# -----------------------------
# Inventory + Extraction
# -----------------------------

@dataclasses.dataclass
class InventoryItem:
    relpath: str
    ext: str
    size_bytes: int
    mtime: float


@dataclasses.dataclass
class ExtractedItem:
    source_relpath: str
    extracted_relpath: str
    text_hash: str
    title_guess: str
    links: List[str]


_LINK_RE = re.compile(r"https?://[^\s\)]+", re.IGNORECASE)


def extract_links(text: str) -> List[str]:
    return sorted(set(_LINK_RE.findall(text)))


def guess_title_from_text(text: str, fallback: str) -> str:
    for line in text.splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith("#"):
            return s.lstrip("#").strip()[:120] or fallback
        return s[:120]
    return fallback


def inventory_legacy(cfg: AppConfig, constraints: Constraints, max_items: int = 0) -> List[InventoryItem]:
    items: List[InventoryItem] = []
    for dirpath, _, filenames in os.walk(cfg.legacy_root):
        for fn in filenames:
            p = Path(dirpath) / fn
            rel = safe_relpath(p.relative_to(cfg.legacy_root))

            # global excludes from config + constraints
            if any(fnmatch.fnmatch(rel, pat) for pat in cfg.exclude_globs):
                continue
            if any(fnmatch.fnmatch(rel, pat) for pat in constraints.global_exclude_patterns):
                continue
            if not any(fnmatch.fnmatch(rel, pat) for pat in cfg.include_globs):
                continue

            st = p.stat()
            items.append(InventoryItem(relpath=rel, ext=p.suffix.lower(), size_bytes=st.st_size, mtime=st.st_mtime))
            if max_items and len(items) >= max_items:
                return items
    return items


def pandoc_to_markdown(cfg: AppConfig, src: Path, media_dir: Path) -> str:
    # Convert to GitHub-flavored Markdown; extract media to a staging dir
    cmd = [
        cfg.tools["pandoc"],
        str(src),
        "-t", "gfm",
        "--wrap=none",
        "--extract-media", str(media_dir),
    ]
    rc, out, err = run_cmd(cmd, cwd=cfg.legacy_root, timeout=300)
    if rc != 0:
        raise RuntimeError(f"pandoc failed ({rc}) for {src}:\n{err}")
    return out


def pdftotext_extract(cfg: AppConfig, src: Path) -> str:
    cmd = [cfg.tools["pdftotext"], "-layout", str(src), "-"]
    rc, out, err = run_cmd(cmd, cwd=cfg.legacy_root, timeout=300)
    if rc != 0:
        raise RuntimeError(f"pdftotext failed ({rc}) for {src}:\n{err}")
    return out


def extract_one(cfg: AppConfig, item: InventoryItem) -> ExtractedItem:
    src = cfg.legacy_root / item.relpath
    extracted_dir = cfg.output_dir / "extracted"
    extracted_dir.mkdir(parents=True, exist_ok=True)

    out_name = item.relpath.replace("/", "__") + ".md"
    extracted_path = extracted_dir / out_name

    data = src.read_bytes()
    src_hash = sha256_bytes(data)
    cache_key = sha256_text(f"extract:v2.1:{item.relpath}:{src_hash}")
    cache_file = cfg.cache_dir / "extract" / f"{cache_key}.json"

    if cache_file.exists() and extracted_path.exists():
        cached = json.loads(read_text(cache_file))
        return ExtractedItem(**cached)

    media_dir = extracted_dir / "media" / out_name.replace(".md", "")
    media_dir.mkdir(parents=True, exist_ok=True)

    if item.ext in [".html", ".htm", ".docx", ".odt", ".rtf"]:
        md = pandoc_to_markdown(cfg, src, media_dir)
    elif item.ext in [".md", ".txt"]:
        md = read_text(src)
    elif item.ext == ".pdf":
        md = pdftotext_extract(cfg, src)
    else:
        md = read_text(src)

    title_guess = guess_title_from_text(md, fallback=Path(item.relpath).stem)
    links = extract_links(md)
    text_hash = sha256_text(md)

    write_text(extracted_path, md)

    result = ExtractedItem(
        source_relpath=item.relpath,
        extracted_relpath=safe_relpath(extracted_path.relative_to(cfg.output_dir)),
        text_hash=text_hash,
        title_guess=title_guess,
        links=links,
    )

    cache_file.parent.mkdir(parents=True, exist_ok=True)
    write_text(cache_file, json.dumps(dataclasses.asdict(result), indent=2))
    return result


# -----------------------------
# Chunking
# -----------------------------

@dataclasses.dataclass
class ChunkItem:
    source_relpath: str
    source_id: str
    chunk_index: int
    chunk_relpath: str
    chunk_hash: str


_HEADING_RE = re.compile(r"^\s{0,3}#{1,6}\s+.+$", re.MULTILINE)


def make_source_id(source_relpath: str) -> str:
    # stable identifier for paths
    return sha256_text("srcid:" + source_relpath)[:16]


def split_by_headings(text: str) -> List[str]:
    """
    If markdown-ish headings exist, split into sections at headings.
    Keep headings with their following content.
    """
    matches = list(_HEADING_RE.finditer(text))
    if len(matches) < 2:
        return [text]

    chunks = []
    for i, m in enumerate(matches):
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        section = text[start:end].strip()
        if section:
            chunks.append(section)
    return chunks or [text]


def chunk_text_fixed(text: str, chunk_chars: int, overlap_chars: int) -> List[str]:
    if len(text) <= chunk_chars:
        return [text]
    chunks = []
    start = 0
    while start < len(text):
        end = min(len(text), start + chunk_chars)
        chunk = text[start:end]
        chunks.append(chunk)
        if end >= len(text):
            break
        start = max(0, end - overlap_chars)
    return chunks


def chunk_extracted(cfg: AppConfig, extracted: ExtractedItem) -> List[ChunkItem]:
    extracted_text = read_text(cfg.output_dir / extracted.extracted_relpath)
    source_id = make_source_id(extracted.source_relpath)

    chunk_chars = int(cfg.chunking.get("chunk_chars", 7000))
    overlap_chars = int(cfg.chunking.get("overlap_chars", 500))
    max_chunks = int(cfg.chunking.get("max_chunks_per_doc", 30))

    # heading split first, then size-normalize
    sections = split_by_headings(extracted_text)
    normalized: List[str] = []
    for sec in sections:
        if len(sec) > chunk_chars * 1.2:
            normalized.extend(chunk_text_fixed(sec, chunk_chars, overlap_chars))
        else:
            normalized.append(sec)

    # cap
    if len(normalized) > max_chunks:
        normalized = normalized[:max_chunks]

    out_dir = cfg.output_dir / "chunks" / source_id
    out_dir.mkdir(parents=True, exist_ok=True)

    chunk_items: List[ChunkItem] = []
    for idx, chunk in enumerate(normalized):
        chunk_hash = sha256_text(chunk)
        chunk_file = out_dir / f"chunk_{idx:03d}.md"
        write_text(chunk_file, chunk)
        chunk_items.append(
            ChunkItem(
                source_relpath=extracted.source_relpath,
                source_id=source_id,
                chunk_index=idx,
                chunk_relpath=safe_relpath(chunk_file.relative_to(cfg.output_dir)),
                chunk_hash=chunk_hash,
            )
        )
    return chunk_items


# -----------------------------
# LLM client (OpenAI-compatible for vLLM)
# -----------------------------

class OpenAICompatClient:
    def __init__(self, base_url: str, api_key: str, model: str):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.model = model

    def chat(self, system: str, user: str, temperature: float, max_tokens: int, timeout_s: int) -> str:
        url = f"{self.base_url}/chat/completions"
        headers = {"Authorization": f"Bearer {self.api_key}"}
        payload = {
            "model": self.model,
            "temperature": temperature,
            "max_tokens": max_tokens,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        }
        r = requests.post(url, headers=headers, json=payload, timeout=timeout_s)
        r.raise_for_status()
        data = r.json()
        return data["choices"][0]["message"]["content"]


def make_llm(cfg: AppConfig) -> OpenAICompatClient:
    llm = cfg.llm
    if llm.get("backend") != "openai_compat":
        raise ValueError("v2.1 expects llm.backend=openai_compat (vLLM or llamafile OpenAI-compatible server).")
    return OpenAICompatClient(
        base_url=llm["openai_compat_url"],
        api_key=llm.get("openai_compat_api_key", "local-no-key"),
        model=llm["model"],
    )


def cached_llm(cfg: AppConfig, namespace: str, key_material: str, call_fn) -> str:
    key = sha256_text(key_material)
    p = cfg.cache_dir / "llm" / namespace / f"{key}.txt"
    if p.exists():
        return read_text(p)
    out = call_fn()
    p.parent.mkdir(parents=True, exist_ok=True)
    write_text(p, out)
    return out


# -----------------------------
# Summarization (chunk + doc)
# -----------------------------

def summarize_chunk(cfg: AppConfig, llm: OpenAICompatClient, chunk: ChunkItem) -> Dict[str, Any]:
    sys_prompt = load_prompt("system.md")
    user_prompt = load_prompt("summarize_chunk.md")
    schema = load_schema("chunk_summary.schema.json")

    chunk_text = read_text(cfg.output_dir / chunk.chunk_relpath)

    key_material = (
        f"sum_chunk:v2.1:{cfg.llm['model']}:{sha256_text(sys_prompt)}:{sha256_text(user_prompt)}:{chunk.chunk_hash}"
    )

    raw = cached_llm(cfg, "sum_chunk", key_material, lambda: llm.chat(
        system=sys_prompt,
        user=f"{user_prompt}\n\nCHUNK:\n---\n{chunk_text}\n---\n\nReturn JSON only.",
        temperature=float(cfg.summarization.get("temperature", 0.1)),
        max_tokens=int(cfg.summarization.get("chunk_summary_tokens", 350)),
        timeout_s=int(cfg.llm.get("timeout_s", 120)),
    ))

    obj = parse_first_json_object(raw)
    jsonschema_validate(instance=obj, schema=schema)

    out_path = cfg.output_dir / "summaries" / "chunk" / chunk.source_id / f"chunk_{chunk.chunk_index:03d}.json"
    write_text(out_path, json.dumps(obj, indent=2))
    return obj


def summarize_doc(cfg: AppConfig, llm: OpenAICompatClient, extracted: ExtractedItem, chunk_summaries: List[Dict[str, Any]]) -> Dict[str, Any]:
    sys_prompt = load_prompt("system.md")
    user_prompt = load_prompt("summarize_doc.md")
    schema = load_schema("doc_summary.schema.json")

    payload = json.dumps(chunk_summaries, indent=2)
    key_material = (
        f"sum_doc:v2.1:{cfg.llm['model']}:{sha256_text(sys_prompt)}:{sha256_text(user_prompt)}:{sha256_text(payload)}"
    )

    raw = cached_llm(cfg, "sum_doc", key_material, lambda: llm.chat(
        system=sys_prompt,
        user=f"{user_prompt}\n\nChunk summaries JSON:\n{payload}\n\nReturn JSON only.",
        temperature=float(cfg.summarization.get("temperature", 0.1)),
        max_tokens=int(cfg.summarization.get("doc_summary_tokens", 450)),
        timeout_s=int(cfg.llm.get("timeout_s", 120)),
    ))

    obj = parse_first_json_object(raw)
    jsonschema_validate(instance=obj, schema=schema)

    source_id = make_source_id(extracted.source_relpath)
    out_path = cfg.output_dir / "summaries" / "doc" / f"{source_id}.json"
    write_text(out_path, json.dumps(obj, indent=2))
    return obj


def load_doc_summary(cfg: AppConfig, source_relpath: str) -> Optional[Dict[str, Any]]:
    source_id = make_source_id(source_relpath)
    p = cfg.output_dir / "summaries" / "doc" / f"{source_id}.json"
    if not p.exists():
        return None
    return json.loads(read_text(p))


# -----------------------------
# Planning (many-to-one) with constraints
# -----------------------------

def canonical_destinations(cfg: AppConfig) -> Dict[str, str]:
    fw = cfg.first_wave
    return {
        "get_started.index": fw["get_started"]["index"],
        "get_started.choose_version": fw["get_started"]["choose_version"],
        "get_started.system_requirements": fw["get_started"]["system_requirements"],
        "get_started.first_experiment": fw["get_started"]["first_experiment"],
        "get_started.troubleshooting": fw["get_started"]["troubleshooting"],
        "teachers.index": fw["teachers"]["index"],
        "teachers.quick_start": fw["teachers"]["quick_start"],
        "students.index": fw["students"]["index"],
        "students.first_steps": fw["students"]["first_steps"],
        "support.index": fw["support"]["index"],
        "support.accessibility": fw["support"]["accessibility"],
        "about.index": fw["about"]["index"],
        "about.how_to_cite": fw["about"]["how_to_cite"],
    }


def validate_dest(cfg: AppConfig, dest: str) -> None:
    if not any(dest.startswith(prefix) for prefix in cfg.allowed_dest_prefixes):
        raise ValueError(f"Invalid dest outside allowed prefixes: {dest}")


def is_archive_candidate(constraints: Constraints, relpath: str) -> bool:
    return any(fnmatch.fnmatch(relpath, pat) for pat in constraints.global_archive_patterns)


def filter_candidates_for_page(
    constraints: Constraints,
    page_type: str,
    extracted: List[ExtractedItem],
) -> List[ExtractedItem]:
    forbid = constraints.forbid_patterns(page_type)
    prefer = constraints.prefer_patterns(page_type)
    forced = set(constraints.force_include(page_type))

    # Start: exclude archive candidates if we're planning a non-archive page
    base = []
    for e in extracted:
        if e.source_relpath in forced:
            base.append(e)
            continue
        # Deprioritize archive-y content in planning by excluding; forced can override
        if is_archive_candidate(constraints, e.source_relpath):
            continue
        # Forbid patterns
        if any(fnmatch.fnmatch(e.source_relpath, pat) for pat in forbid):
            continue
        base.append(e)

    # If prefer patterns exist, keep all but we will sort with prefers first
    def pref_score(e: ExtractedItem) -> int:
        if e.source_relpath in forced:
            return 100
        if any(fnmatch.fnmatch(e.source_relpath.lower(), pat.lower()) for pat in prefer):
            return 10
        # mild heuristic: teacher/student tokens in title/path
        s = (e.source_relpath + " " + e.title_guess).lower()
        if page_type.startswith("teachers.") and "teacher" in s:
            return 5
        if page_type.startswith("students.") and "student" in s:
            return 5
        if page_type.startswith("get_started.") and ("start" in s or "install" in s or "launch" in s):
            return 5
        return 0

    base.sort(key=pref_score, reverse=True)
    return base


def plan_pages(
    cfg: AppConfig,
    llm: OpenAICompatClient,
    constraints: Constraints,
    extracted: List[ExtractedItem],
    page_types: List[str],
) -> List[Dict[str, Any]]:
    sys_prompt = load_prompt("system.md")
    planner_prompt = load_prompt("planner.md")
    schema = load_schema("page_plan.schema.json")
    canon = canonical_destinations(cfg)

    plans: List[Dict[str, Any]] = []
    for page_type in page_types:
        if page_type not in canon:
            continue

        dest = constraints.dest_override(page_type) or canon[page_type]
        validate_dest(cfg, dest)

        candidates = filter_candidates_for_page(constraints, page_type, extracted)

        # Build candidate summaries payload; if doc summary missing, include minimal fallback
        candidate_payload = []
        for e in candidates:
            ds = load_doc_summary(cfg, e.source_relpath)
            candidate_payload.append({
                "source": e.source_relpath,
                "title_guess": e.title_guess,
                "doc_summary": ds if ds is not None else {
                    "doc_title_guess": e.title_guess,
                    "audience": "unknown",
                    "content_type": "unknown",
                    "best_use": "unknown",
                    "key_points": [],
                    "still_relevant": [],
                    "likely_outdated": [],
                    "notable_links": e.links[:10],
                }
            })

        forced = constraints.force_include(page_type)
        forbid = constraints.forbid_patterns(page_type)

        user = (
            f"{planner_prompt}\n\n"
            f"Target page_type: {page_type}\n"
            f"Destination (repo-relative): {dest}\n\n"
            f"Constraints:\n"
            f"- force_include: {json.dumps(forced)}\n"
            f"- forbid_patterns: {json.dumps(forbid)}\n\n"
            f"Candidates (with doc_summary):\n{json.dumps(candidate_payload, indent=2)[:200000]}\n\n"
            f"Return JSON only."
        )

        key_material = (
            f"plan:v2.1:{cfg.llm['model']}:{page_type}:"
            f"{sha256_text(sys_prompt)}:{sha256_text(planner_prompt)}:{sha256_text(user)}"
        )

        raw = cached_llm(cfg, "plan", key_material, lambda: llm.chat(
            system=sys_prompt,
            user=user,
            temperature=float(cfg.llm.get("temperature", 0.2)),
            max_tokens=1800,
            timeout_s=int(cfg.llm.get("timeout_s", 120)),
        ))

        obj = parse_first_json_object(raw)
        jsonschema_validate(instance=obj, schema=schema)

        # Enforce page_type + dest
        obj["page_type"] = page_type
        obj["dest"] = dest
        obj["page_id"] = obj.get("page_id") or page_type.replace(".", "_")

        # Enforce forced includes if present in extracted
        available_sources = set(e.source_relpath for e in extracted)
        forced_present = [s for s in forced if s in available_sources]
        sf = list(dict.fromkeys(obj.get("source_files", [])))

        # Remove forbidden patterns post-hoc
        def allowed_source(s: str) -> bool:
            return not any(fnmatch.fnmatch(s, pat) for pat in forbid)

        sf = [s for s in sf if allowed_source(s)]
        for s in forced_present:
            if s not in sf:
                sf.insert(0, s)

        if not sf:
            # fail safe: if nothing left, create a minimal plan with forced only or mark warnings
            sf = forced_present[:]
            obj["warnings"] = list(dict.fromkeys(obj.get("warnings", []) + ["Planner returned no usable sources; using forced sources only."]))

        obj["source_files"] = sf

        so = [s for s in obj.get("source_order", []) if s in sf]
        if not so:
            so = sf[:]
        obj["source_order"] = so

        # Required sections must exist
        if "required_sections" not in obj or not isinstance(obj["required_sections"], list):
            obj["required_sections"] = []

        plans.append(obj)

    return plans


# -----------------------------
# Evidence chunk selection (deterministic)
# -----------------------------

def load_chunk_items_for_source(cfg: AppConfig, source_relpath: str) -> List[ChunkItem]:
    source_id = make_source_id(source_relpath)
    chunks_dir = cfg.output_dir / "chunks" / source_id
    if not chunks_dir.exists():
        return []
    items = []
    for p in sorted(chunks_dir.glob("chunk_*.md")):
        idx = int(p.stem.split("_")[1])
        txt = read_text(p)
        items.append(ChunkItem(
            source_relpath=source_relpath,
            source_id=source_id,
            chunk_index=idx,
            chunk_relpath=safe_relpath(p.relative_to(cfg.output_dir)),
            chunk_hash=sha256_text(txt),
        ))
    return items


def pick_evidence_chunks(cfg: AppConfig, plan: Dict[str, Any], source_relpath: str, k: int = 2) -> List[ChunkItem]:
    """
    Deterministic evidence selection:
    - prefer first chunk
    - plus one chunk with keyword overlap (if possible), else second chunk
    """
    chunks = load_chunk_items_for_source(cfg, source_relpath)
    if not chunks:
        return []

    required_sections = " ".join(plan.get("required_sections", [])).lower()
    keywords = set(re.findall(r"[a-zA-Z]{4,}", required_sections))  # crude but stable

    def score(chunk: ChunkItem) -> int:
        txt = read_text(cfg.output_dir / chunk.chunk_relpath).lower()
        return sum(1 for kw in keywords if kw in txt)

    ranked = sorted(chunks, key=score, reverse=True)
    chosen = []
    chosen.append(chunks[0])
    if k > 1:
        best = ranked[0]
        if best.chunk_index != chunks[0].chunk_index:
            chosen.append(best)
        elif len(chunks) > 1:
            chosen.append(chunks[1])
    return chosen[:k]


# -----------------------------
# Drafting (synthesis) using summaries + evidence
# -----------------------------

def draft_from_plan(cfg: AppConfig, llm: OpenAICompatClient, plan: Dict[str, Any]) -> Dict[str, Any]:
    sys_prompt = load_prompt("system.md")
    rw_prompt = load_prompt("rewriter_synthesis.md")
    schema = load_schema("page_draft.schema.json")

    # Build ordered sources: doc summaries always + a couple evidence chunks
    blocks: List[str] = []
    for src in plan["source_order"]:
        ds = load_doc_summary(cfg, src)
        ds_json = json.dumps(ds, indent=2) if ds else "{}"
        blocks.append(f"## SOURCE: {src}\n\nDOC_SUMMARY_JSON:\n{ds_json}\n")
        for ev in pick_evidence_chunks(cfg, plan, src, k=2):
            ev_text = read_text(cfg.output_dir / ev.chunk_relpath)
            blocks.append(f"### EVIDENCE_CHUNK: {src} :: {Path(ev.chunk_relpath).name}\n\n{ev_text}\n")

    user = (
        f"{rw_prompt}\n\n"
        f"PagePlan JSON:\n{json.dumps(plan, indent=2)}\n\n"
        f"Ordered sources with summaries and evidence:\n\n"
        + "\n---\n".join(blocks)
        + "\n\nReturn JSON object first, then the exact Markdown."
    )

    key_material = (
        f"draft:v2.1:{cfg.llm['model']}:{plan['page_type']}:"
        f"{sha256_text(sys_prompt)}:{sha256_text(rw_prompt)}:{sha256_text(user)}"
    )

    raw = cached_llm(cfg, "draft", key_material, lambda: llm.chat(
        system=sys_prompt,
        user=user,
        temperature=float(cfg.llm.get("temperature", 0.2)),
        max_tokens=int(cfg.llm.get("max_tokens", 2500)),
        timeout_s=int(cfg.llm.get("timeout_s", 120)),
    ))

    obj = parse_first_json_object(raw)
    jsonschema_validate(instance=obj, schema=schema)

    # Enforce dest + sources
    obj["dest"] = plan["dest"]
    obj["source_files"] = plan["source_files"]
    obj["generated_marker"] = True

    # Enforce generated marker
    md = obj["markdown"].lstrip()
    if not md.startswith(GENERATED_MARKER):
        md = GENERATED_MARKER + "\n\n" + md
    # Enforce sources comment
    if "<!-- Sources:" not in md:
        md = md.rstrip() + "\n\n<!-- Sources: " + "; ".join(plan["source_files"]) + " -->\n"
    obj["markdown"] = md

    return obj


# -----------------------------
# Linkmap + link repair
# -----------------------------

_MD_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


def build_linkmap(plans: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Conservative deterministic mapping:
    legacy source file path -> new doc path (dest) for sources included in plans.
    """
    entries = []
    assigned: Dict[str, str] = {}
    for plan in plans:
        dest = plan["dest"]
        for src in plan["source_files"]:
            assigned.setdefault(src, dest)

    for legacy_src, new_dest in assigned.items():
        entries.append({"legacy_ref": legacy_src, "new_ref": "/" + new_dest.replace("docs/", "docs/"), "confidence": 0.95})

    return {"generated_at": now_iso(), "entries": entries}


def rewrite_links_in_markdown(md: str, linkmap: Dict[str, Any]) -> Tuple[str, List[str]]:
    warnings: List[str] = []
    lookup: Dict[str, str] = {}
    for e in linkmap.get("entries", []):
        legacy = e["legacy_ref"]
        new_ref = e["new_ref"]
        lookup[legacy] = new_ref
        lookup[legacy.lstrip("./")] = new_ref
        lookup[legacy.replace("\\", "/")] = new_ref

    def repl(m):
        text, target = m.group(1), m.group(2).strip()
        anchor = ""
        tnorm = target
        if "#" in tnorm:
            tnorm, a = tnorm.split("#", 1)
            anchor = "#" + a
        key = tnorm.lstrip("./")
        if key in lookup:
            return f"[{text}]({lookup[key]}{anchor})"
        return m.group(0)

    patched = _MD_LINK.sub(repl, md)

    # Heuristic warnings
    if ".html" in patched or ".htm" in patched:
        warnings.append("Some legacy .html links remain; review for manual mapping.")
    if "click here" in patched.lower():
        warnings.append("Found non-descriptive link text ('click here'); revise.")
    return patched, warnings


# -----------------------------
# Apply pages (strict overwrite)
# -----------------------------

def can_overwrite(dest: Path) -> bool:
    if not dest.exists():
        return True
    head = read_text(dest)[:5000]
    return GENERATED_MARKER in head


def apply_page(cfg: AppConfig, draft: Dict[str, Any], dry_run: bool, overwrite: bool) -> Path:
    dest_path = cfg.target_repo_root / draft["dest"]

    if dest_path.exists():
        if not overwrite:
            raise FileExistsError(f"Refusing overwrite (overwrite=false): {dest_path}")
        if not can_overwrite(dest_path):
            raise PermissionError(f"Refusing overwrite: missing generated marker: {dest_path}")

    if dry_run:
        return dest_path

    write_text(dest_path, draft["markdown"])
    return dest_path


# -----------------------------
# QA
# -----------------------------

def run_qa(cfg: AppConfig) -> None:
    for cmd in cfg.pipeline.get("qa_commands", []):
        rc, out, err = run_cmd(cmd, cwd=cfg.target_repo_root, timeout=900)
        if rc != 0:
            raise RuntimeError(f"QA failed: {cmd}\nSTDOUT:\n{out}\nSTDERR:\n{err}")


# -----------------------------
# CLI and pipeline
# -----------------------------

def parse_csv_list(s: str) -> List[str]:
    s = (s or "").strip()
    if not s:
        return []
    return [x.strip() for x in s.split(",") if x.strip()]


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        return []
    return [json.loads(line) for line in read_text(path).splitlines() if line.strip()]


def save_jsonl(path: Path, rows: List[Dict[str, Any]]) -> None:
    write_text(path, "\n".join(json.dumps(r) for r in rows) + ("\n" if rows else ""))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(HERE / "config.yaml"))
    ap.add_argument("--max-items", type=int, default=0)
    ap.add_argument("--page-types", default="", help="Comma-separated list of page_types to run (subset).")

    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("inventory")
    sub.add_parser("extract")
    sub.add_parser("chunk")
    sub.add_parser("summarize")
    sub.add_parser("plan")
    sub.add_parser("draft")
    sub.add_parser("linkmap")
    sub.add_parser("repair-links")
    sub.add_parser("apply")
    sub.add_parser("qa")

    p_run = sub.add_parser("run")
    p_run.add_argument("--dry-run", default="true")
    p_run.add_argument("--overwrite", default="false")

    args = ap.parse_args()

    cfg = load_config(Path(args.config))
    constraints = Constraints.load(cfg.constraints_file)

    cfg.output_dir.mkdir(parents=True, exist_ok=True)
    cfg.cache_dir.mkdir(parents=True, exist_ok=True)

    llm = make_llm(cfg)

    max_items = args.max_items or int(cfg.pipeline.get("max_items", 0) or 0)
    page_types_filter = set(parse_csv_list(args.page_types))

    inv_path = cfg.output_dir / "inventory.jsonl"
    ext_idx_path = cfg.output_dir / "extracted_index.jsonl"
    chunks_idx_path = cfg.output_dir / "chunks_index.jsonl"
    plans_path = cfg.output_dir / "plans.jsonl"
    drafts_path = cfg.output_dir / "drafts_index.jsonl"
    linkmap_path = cfg.output_dir / "linkmap.json"
    report_path = cfg.output_dir / "report.md"

    notes: List[str] = []

    # Determine page_types to target (canonical list, optionally filtered)
    canon = canonical_destinations(cfg)
    target_page_types = list(canon.keys())
    if page_types_filter:
        target_page_types = [pt for pt in target_page_types if pt in page_types_filter]

    # -------------------------
    # Stage: inventory
    # -------------------------
    if args.cmd in ("inventory", "run"):
        inv_items = inventory_legacy(cfg, constraints, max_items=max_items)
        save_jsonl(inv_path, [dataclasses.asdict(i) for i in inv_items])
    else:
        inv_items = [InventoryItem(**r) for r in load_jsonl(inv_path)]

    # -------------------------
    # Stage: extract
    # -------------------------
    if args.cmd in ("extract", "run"):
        extracted_items: List[ExtractedItem] = []
        for i in inv_items[: max_items or len(inv_items)]:
            try:
                extracted_items.append(extract_one(cfg, i))
            except Exception as e:
                notes.append(f"EXTRACT FAIL: {i.relpath}: {e}")
        save_jsonl(ext_idx_path, [dataclasses.asdict(e) for e in extracted_items])
    else:
        extracted_items = [ExtractedItem(**r) for r in load_jsonl(ext_idx_path)]

    # -------------------------
    # Stage: chunk
    # -------------------------
    if args.cmd in ("chunk", "run"):
        chunk_items: List[ChunkItem] = []
        for e in extracted_items[: max_items or len(extracted_items)]:
            try:
                chunk_items.extend(chunk_extracted(cfg, e))
            except Exception as ex:
                notes.append(f"CHUNK FAIL: {e.source_relpath}: {ex}")
        save_jsonl(chunks_idx_path, [dataclasses.asdict(c) for c in chunk_items])
    else:
        chunk_items = [ChunkItem(**r) for r in load_jsonl(chunks_idx_path)]

    # Group chunks by source_id
    chunks_by_source: Dict[str, List[ChunkItem]] = {}
    for c in chunk_items:
        chunks_by_source.setdefault(c.source_id, []).append(c)
    for k in list(chunks_by_source.keys()):
        chunks_by_source[k].sort(key=lambda x: x.chunk_index)

    # -------------------------
    # Stage: summarize (chunk + doc)
    # -------------------------
    if args.cmd in ("summarize", "run"):
        # Summarize each chunk, then summarize docs
        extracted_by_src = {e.source_relpath: e for e in extracted_items}

        for e in extracted_items[: max_items or len(extracted_items)]:
            src = e.source_relpath
            source_id = make_source_id(src)
            chunks = chunks_by_source.get(source_id, [])
            if not chunks:
                notes.append(f"SUMMARIZE SKIP: no chunks for {src}")
                continue

            chunk_summaries: List[Dict[str, Any]] = []
            for ch in chunks:
                # If already written, load it (avoid re-LLM on reruns)
                sp = cfg.output_dir / "summaries" / "chunk" / ch.source_id / f"chunk_{ch.chunk_index:03d}.json"
                if sp.exists():
                    chunk_summaries.append(json.loads(read_text(sp)))
                    continue
                try:
                    chunk_summaries.append(summarize_chunk(cfg, llm, ch))
                except Exception as ex:
                    notes.append(f"SUMMARIZE CHUNK FAIL: {src} chunk {ch.chunk_index}: {ex}")

            # Doc summary
            dp = cfg.output_dir / "summaries" / "doc" / f"{source_id}.json"
            if not dp.exists():
                try:
                    summarize_doc(cfg, llm, e, chunk_summaries)
                except Exception as ex:
                    notes.append(f"SUMMARIZE DOC FAIL: {src}: {ex}")
    else:
        # no-op: summaries are loaded on demand
        pass

    # -------------------------
    # Stage: plan (many-to-one)
    # -------------------------
    if args.cmd in ("plan", "run"):
        try:
            plans = plan_pages(cfg, llm, constraints, extracted_items, target_page_types)
            save_jsonl(plans_path, plans)
        except Exception as ex:
            notes.append(f"PLAN FAIL: {ex}")
            plans = []
    else:
        plans = load_jsonl(plans_path)

    # -------------------------
    # Stage: draft
    # -------------------------
    if args.cmd in ("draft", "run"):
        schema = load_schema("page_draft.schema.json")
        drafts: List[Dict[str, Any]] = []

        # Filter plans by page_types filter if set
        plans_to_run = plans
        if page_types_filter:
            plans_to_run = [p for p in plans if p.get("page_type") in page_types_filter]

        for plan in plans_to_run:
            try:
                d = draft_from_plan(cfg, llm, plan)
                jsonschema_validate(instance=d, schema=schema)
                drafts.append(d)
            except Exception as ex:
                notes.append(f"DRAFT FAIL: {plan.get('dest')}: {ex}")

        save_jsonl(drafts_path, drafts)
    else:
        drafts = load_jsonl(drafts_path)

    # -------------------------
    # Stage: linkmap
    # -------------------------
    if args.cmd in ("linkmap", "run"):
        lm = build_linkmap(plans)
        write_text(linkmap_path, json.dumps(lm, indent=2))
    else:
        lm = json.loads(read_text(linkmap_path)) if linkmap_path.exists() else {"generated_at": now_iso(), "entries": []}

    # -------------------------
    # Stage: repair-links
    # -------------------------
    if args.cmd in ("repair-links", "run"):
        patched: List[Dict[str, Any]] = []
        for d in drafts:
            md, warns = rewrite_links_in_markdown(d["markdown"], lm)
            d2 = dict(d)
            d2["markdown"] = md
            d2["warnings"] = list(dict.fromkeys(d2.get("warnings", []) + warns))
            patched.append(d2)
        drafts = patched
        save_jsonl(drafts_path, drafts)

    # -------------------------
    # Stage: apply
    # -------------------------
    if args.cmd in ("apply", "run"):
        dry_run = (getattr(args, "dry_run", "true").lower() == "true")
        overwrite = (getattr(args, "overwrite", "false").lower() == "true")
        applied = 0

        # Filter drafts by page_types filter if set
        drafts_to_apply = drafts
        if page_types_filter:
            drafts_to_apply = [d for d in drafts if d.get("dest") and any(d.get("dest","").startswith(canon[pt].split("/")[0]) for pt in page_types_filter) ]

        for d in drafts_to_apply:
            try:
                apply_page(cfg, d, dry_run=dry_run, overwrite=overwrite)
                applied += 1
            except Exception as ex:
                notes.append(f"APPLY FAIL: {d.get('dest')}: {ex}")

        notes.append(f"{'Dry run: would write' if dry_run else 'Wrote'} {applied} pages.")
        if cfg.pipeline.get("run_qa", False) and not dry_run:
            try:
                run_qa(cfg)
            except Exception as ex:
                notes.append(f"QA FAIL: {ex}")

    if args.cmd == "qa":
        run_qa(cfg)

    # -------------------------
    # Report
    # -------------------------
    lines: List[str] = []
    lines.append("# Migration report (v2.1)\n\n")
    lines.append(f"- Generated: `{now_iso()}`\n")
    lines.append(f"- Legacy root: `{cfg.legacy_root}`\n")
    lines.append(f"- Target repo root: `{cfg.target_repo_root}`\n\n")

    lines.append("## Counts\n")
    lines.append(f"- inventory: {len(inv_items)}\n")
    lines.append(f"- extracted: {len(extracted_items)}\n")
    lines.append(f"- chunks: {len(chunk_items)}\n")
    lines.append(f"- plans: {len(plans)}\n")
    lines.append(f"- drafts: {len(drafts)}\n\n")

    if notes:
        lines.append("## Notes\n")
        for n in notes:
            lines.append(f"- {n}\n")
        lines.append("\n")

    write_text(report_path, "".join(lines))
    print(f"[ok] report: {report_path}")


if __name__ == "__main__":
    main()
